### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jeremyjs** [jjman505/afs#1]
- [ ] Shelters
  - [ ] Listing
  - [ ] Find a shelter
    - [ ] Search by zipcode
    - [ ] Google map of nearby shelters
  - [ ] Registration (requires verification by AFS)
  - [ ] Public profile
    - [ ] Updates section for the shelter, like a FB timeline
    - [ ] Campaign mini profile and link to main campaign profile
  - [ ] Edit profile (Admins only)
    - [ ] Add new admins
  - [ ] Edit inventory (Admins only)
- [ ] Users
  - [ ] Listing?
  - [ ] Account registration
  - [ ] Sign in
  - [ ] User profile?
  - [ ] Edit profile?
- [ ] Communities
  - [ ] Listing/Find a community
  - [ ] Create a community
  - [ ] Public profile
    - [ ] Join a community
  - [ ] Edit profile (Admins only)
    - [ ] Invite people to join
- [ ] Campaigns
  - [ ] Listing/Find a campaign
  - [ ] Create a campaign (Community or Shelter Admins only?)
  - [ ] Public profile
    - [ ] Join a campaign
    - [ ] See the progress (tally count of donations)
  - [ ] Edit profile
    - [ ] Invite people to join

**Comment by jeremyjs** [comment]
@jstannard How does this look? The things with question marks, should we implement them or leave them out? Is there anything else missing?

**Comment by jaesulli95** [comment]
Theres another layer of security I think @jstannard would want, and that is to make it to where the shelters have to be verified by A Fresh Start, to ensure they actually exist.

**Comment by jstannard** [comment]
Good point from both of you, yes I want to make sure that after shelters create profiles that it says something like "thank you for creating a profile. your submission is pending" then I can go in and accept or deny it. Jeremy when you say users do you mean anyone who is not affiliated with a corporation basically an individually creating a drive? Their listing would be what?

**Comment by jeremyjs** [comment]
@jstannard Admins for the pages will be regular users with extra permissions. We can easily add two-step verification to make sure they are who they say they are. Regular users could just be donators, but we'll want them to create an account so we can easily track the donations and be able to send updates on their local shelters and so forth. The point is that every user is a person, and a page is a separate entity managed by users. How do you feel about that?

**Comment by jstannard** [comment]
@jjman505 sounds good to me
